# Generated by Django 4.1.4 on 2023-06-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_alimento_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='precio',
            field=models.IntegerField(blank=True, default=0, verbose_name='Precio'),
        ),
    ]
