# Generated by Django 4.2.1 on 2023-07-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0004_boleta_alter_alimento_imagen_detalle_boleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='stock',
            field=models.IntegerField(blank=True, default=0, verbose_name='Cantidad de Productos'),
        ),
    ]
