# Generated by Django 4.2.1 on 2023-07-12 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0006_boleta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='usuario',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
