# Generated by Django 4.2.1 on 2023-07-12 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0008_alter_alimento_cod'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_boleta',
            name='nombre',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
