# Generated by Django 4.2.1 on 2023-07-12 02:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0009_detalle_boleta_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='stock',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, 'El valor mínimo para el stock es 0.')], verbose_name='Cantidad de Productos'),
        ),
    ]
